# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dae7682540d8d7ce778ef9771565d88ccab6f83471fd6b014009ff7e617a41b8b724ff44a93a808e3ac61383bc0b01efc44982ccc78f10d31efdc97a5fb91a7

test:
  secret_key_base: 5f047a5b45ba5e2e7a307f094efdef54ead28a4cad2cd681a5f98c3106c1c026c0502ff1003140104527db70ac9a23e8fa3b88b18eeefef695becb57abf6faca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
